#ifndef LOGGER_CONFIG_H_
#define LOGGER_CONFIG_H_

#define LOG_ENABLE 1
#define LOG_LAST_CHANNEL 255
#define DEFAULT_LOG_CHANNEL_LEVEL LOG_LEVEL_DEBUG

#define CAMERA_LOG_CHANNEL 2
#define CAMERA_LOG_CHANNEL_LEVEL LOG_LEVEL_DEBUG

#define KITTY_LOG_CHANNEL       2
#define KITTY_LOG_CHANNEL_LEVEL LOG_LEVEL_NOTICE

#define MENU_LOG_CHANNEL 2
#define MENU_LOG_CHANNEL_LEVEL LOG_LEVEL_DEBUG

#define PIXY_LOG_CHANNEL 5
#define PIXY_LOG_CHANNEL_LEVEL LOG_LEVEL_ERROR

#define MOTOR_LOG_CHANNEL 2
#define MOTOR_LOG_CHANNEL_LEVEL LOG_LEVEL_DEBUG

#define SENSOR_LOG_CHANNEL 2
#define SENSOR_LOG_CHANNEL_LEVEL LOG_LEVEL_DEBUG

#define TRACK_LOG_CHANNEL 4
#define TRACK_LOG_CHANNEL_LEVEL LOG_LEVEL_DEBUG

#endif